// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Contoso.Expenses.APIClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for ContosoExpensesAPI.
    /// </summary>
    public static partial class ContosoExpensesAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='submitterEmail'>
            /// </param>
            public static CostCenterInfo GetCostCenterInfo(this IContosoExpensesAPI operations, string submitterEmail)
            {
                return operations.GetCostCenterInfoAsync(submitterEmail).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='submitterEmail'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CostCenterInfo> GetCostCenterInfoAsync(this IContosoExpensesAPI operations, string submitterEmail, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCostCenterInfoWithHttpMessagesAsync(submitterEmail, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
