apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: conexp-triggertemplate
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: web-imageUrl
      description: Url of image repository
    - name: api-imageUrl
      description: Url of image repository
    - name: namespace
      description: The namespace to create the resources
    - name: deployment-namespace
      description: The namespace to deploy the yaml
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: conexp-pipeline-run-$(uid)
        namespace: $(params.namespace)
      spec:
        serviceAccountName: deployment-user
        pipelineRef:
          name: conexp-pipeline
        params:
          - name: deployment-namespace
            value: $(params.deployment-namespace)
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(params.gitrevision)
              - name: url
                value: $(params.gitrepositoryurl)
          - name: web-image-source
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(params.web-imageUrl)
          - name: api-image-source
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(params.api-imageUrl)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: conexp-pipelinebinding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: conexp-devops
    - name: deployment-namespace
      value: conexp
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: web-imageUrl
      value: "harbor.aks.srinipadala.xyz/lab/conexp-web:$(body.head_commit.id)"
    - name: api-imageUrl
      value: "harbor.aks.srinipadala.xyz/lab/conexp-api:$(body.head_commit.id)"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: conexp-listener
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - name: conexp-pipelinebinding
      template:
        name: conexp-triggertemplate
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/docker-0: https://harbor.aks.srinipadala.xyz
type: kubernetes.io/basic-auth
stringData:
  username: lab-admin
  password: Sr!n!433
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-user
secrets:
  - name: basic-user-pass
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: deployment-user