// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Contoso.Expenses.APIClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CostCenterInfo
    {
        /// <summary>
        /// Initializes a new instance of the CostCenterInfo class.
        /// </summary>
        public CostCenterInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CostCenterInfo class.
        /// </summary>
        public CostCenterInfo(string submitterEmail = default(string), string approverEmail = default(string), string costCenter = default(string))
        {
            SubmitterEmail = submitterEmail;
            ApproverEmail = approverEmail;
            CostCenter = costCenter;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "submitterEmail")]
        public string SubmitterEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "approverEmail")]
        public string ApproverEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "costCenter")]
        public string CostCenter { get; set; }

    }
}
